//! Cross-language compatibility tests.
//! Reads fixtures generated by Go, Python, and TypeScript.

use golf::reader::GolfReader;
use std::path::PathBuf;

fn testdata_dir() -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("../testdata")
}

/// Helper to test a "small" fixture (20 records, value_size=8, no compression).
fn assert_small_fixture(path: &std::path::Path) {
    let mut reader = GolfReader::open_path(path).unwrap();
    assert_eq!(reader.record_count(), 20);
    assert_eq!(reader.header().record_value_size, 8);

    let result = reader.query(0, 19000).unwrap();
    assert_eq!(result.len(), 20);
    assert_eq!(result[0].timestamp, 0);
    assert_eq!(result[0].value[0], 0);
    assert_eq!(result[19].timestamp, 19000);
    assert_eq!(result[19].value[0], 19);
}

/// Helper to test an "lz4" fixture (100 records, value_size=16, LZ4).
fn assert_lz4_fixture(path: &std::path::Path) {
    let mut reader = GolfReader::open_path(path).unwrap();
    assert_eq!(reader.record_count(), 100);
    assert_eq!(reader.header().record_value_size, 16);

    let result = reader.query(0, 49500).unwrap();
    assert_eq!(result.len(), 100);

    // Spot check a range
    let result = reader.query(5000, 10000).unwrap();
    assert_eq!(result.len(), 11);
}

/// Helper to test a "metadata" fixture (10 records, with metadata).
fn assert_metadata_fixture(path: &std::path::Path, expected_source: &str) {
    let reader = GolfReader::open_path(path).unwrap();
    assert_eq!(reader.record_count(), 10);
    let meta = reader.metadata();
    assert_eq!(meta.len(), 2);
    assert_eq!(meta[0].key, "source");
    assert_eq!(meta[0].value, expected_source);
    assert_eq!(meta[1].key, "version");
}

// ── Rust fixtures ──

#[test]
fn test_read_rust_small() {
    assert_small_fixture(&testdata_dir().join("small.golf"));
}

#[test]
fn test_read_rust_metadata() {
    assert_metadata_fixture(&testdata_dir().join("with_metadata.golf"), "fixture-generator");
}

// ── Go fixtures ──

#[test]
fn test_read_go_small() {
    let path = testdata_dir().join("go_small.golf");
    if !path.exists() {
        eprintln!("Skipping: {:?} not found", path);
        return;
    }
    assert_small_fixture(&path);
}

#[test]
fn test_read_go_lz4() {
    let path = testdata_dir().join("go_lz4.golf");
    if !path.exists() {
        eprintln!("Skipping: {:?} not found", path);
        return;
    }
    assert_lz4_fixture(&path);
}

#[test]
fn test_read_go_metadata() {
    let path = testdata_dir().join("go_metadata.golf");
    if !path.exists() {
        eprintln!("Skipping: {:?} not found", path);
        return;
    }
    assert_metadata_fixture(&path, "go-generator");
}

// ── Python fixtures ──

#[test]
fn test_read_python_small() {
    let path = testdata_dir().join("py_small.golf");
    if !path.exists() {
        eprintln!("Skipping: {:?} not found", path);
        return;
    }
    assert_small_fixture(&path);
}

#[test]
fn test_read_python_lz4() {
    let path = testdata_dir().join("py_lz4.golf");
    if !path.exists() {
        eprintln!("Skipping: {:?} not found", path);
        return;
    }
    assert_lz4_fixture(&path);
}

#[test]
fn test_read_python_metadata() {
    let path = testdata_dir().join("py_metadata.golf");
    if !path.exists() {
        eprintln!("Skipping: {:?} not found", path);
        return;
    }
    assert_metadata_fixture(&path, "python-generator");
}

// ── TypeScript fixtures ──

#[test]
fn test_read_typescript_small() {
    let path = testdata_dir().join("ts_small.golf");
    if !path.exists() {
        eprintln!("Skipping: {:?} not found", path);
        return;
    }
    assert_small_fixture(&path);
}

#[test]
fn test_read_typescript_lz4() {
    let path = testdata_dir().join("ts_lz4.golf");
    if !path.exists() {
        eprintln!("Skipping: {:?} not found", path);
        return;
    }
    assert_lz4_fixture(&path);
}

#[test]
fn test_read_typescript_metadata() {
    let path = testdata_dir().join("ts_metadata.golf");
    if !path.exists() {
        eprintln!("Skipping: {:?} not found", path);
        return;
    }
    assert_metadata_fixture(&path, "typescript-generator");
}
